steps:
  # Retrieve a container image to use the cache of.
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull gcr.io/$PROJECT_ID/rustysnake:latest || exit 0"]
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/rustysnake:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/rustysnake:latest",
        "--cache-from",
        "gcr.io/$PROJECT_ID/rustysnake:latest",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/rustysnake:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "rustysnake"
      - "--image"
      - "gcr.io/$PROJECT_ID/rustysnake:$COMMIT_SHA"
      - "--region"
      - "us-west2"
images:
  - "gcr.io/$PROJECT_ID/rustysnake:$COMMIT_SHA"
